### ISSUE TITLE
`eris clean`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#209]
fork of #207 
- [x] stop & kill any containers (incl their volumes)
- [x] flag for volumes (for #270) 
- [ ] rework [bash script](https://github.com/chadoe/docker-cleanup-volumes/blob/master/docker-cleanup-volumes.sh) for orphaned volumes (moved to #295) 
- [x] flag for images. list all, regex for "eris"
- [x] include test
- [ ] uninstall (rm binary? delete `/eris-cli`?) (moved to #295)

**Comment by zramsay** [comment]
- [ ] refactor & move to /util

**Comment by zramsay** [comment]
and use #258 / #302
