### ISSUE TITLE
major init refactor

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#309]
- [x] use toadserver for pulling in definition files
- [x] build test coverage #251 
- [x] `eris init --dir` -> #377, for testing (rejected)
- [x] `eris init --pull-images` -> #112, main images for tool pipeline
   - `eris/base`
   - `eris/keys`
   - `eris/data`
   - `eris/erisdb`
   - `eris/epm`
   - `eris/ipfs`
- [x] drop fresh priv_val/keypair, config.toml, & genesis.json -> #357  (relegated to `make`)
- [x] add a few "tour" directions (TODO, after `make`)

**Comment by zramsay** [comment]
could not replicate but re-naming to more relevant issue

**Comment by zramsay** [comment]
related to #251

**Comment by compleatang** [comment]
related to #291

**Comment by zramsay** [comment]
hm, for #357, we're gonna need some images (all save for `epm` and maybe `data`), so might as well pull 'em all! init should also compare latest quay images with local ones and pull in latest (see also #375)

**Comment by compleatang** [comment]
My feeling is that it is best just to :dowit: once during that init (as long as we make sure that user's approve the giant bandwidth), so then it is done. It will take a while if they don't have anything but they can go `feed their marmots` or drink a cuppa... :cocktail: :coffee: :beers:

**Comment by zramsay** [comment]
:yodawg: i hard you like pulling 5 gigs worth of images in `init`
