### ISSUE TITLE
refactor listing functions

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#376]
- [zr]
- [ ] replace the `Type` field in the listing functions with `Machine` using [libmachine](https://godoc.org/github.com/docker/machine/libmachine/host) #371 (defered)
- [x] `eris keys ls` => #401 
- [x] `eris data ls` => for host/container (#339) [zr]: rejected because #400

**Comment by zramsay** [comment]
oh maybe we replace that header with `MACHINE` for #371

**Comment by compleatang** [comment]
nice. like it.

**Comment by zramsay** [comment]
closed by #457l; doesn't include machine field...postponed until `remotes ls` takes hold.
